# Generated by Django 4.2.3 on 2023-08-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_special_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="task_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
