# Generated by Django 3.2.3 on 2021-12-22 17:01

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('national_code', models.CharField(max_length=10)),
                ('birthday_date', django_jalali.db.models.jDateField()),
                ('ceremony_datetime', django_jalali.db.models.jDateTimeField()),
            ],
        ),
    ]
