# Generated by Django 5.0.6 on 2024-08-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ceremony_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Iran', max_length=256),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
